# Dockerfile-nginx

FROM nginx:latest

# nginx will listen on this port
EXPOSE 80

# remove the default config file that /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf

# copy our nginx.conf
COPY nginx-app.conf /etc/nginx/conf.d
